global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-hashicorp-nomad
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  nomad:
    parameter_input: quickstart-hashicorp-nomad.json
    template_file: quickstart-hashicorp-nomad-master.template
    regions:
     - us-east-1
